// <auto-generated />
using System;
using Esraa_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Esraa_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210423140304_EsraaSto")]
    partial class EsraaSto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Esraa_Store.Models.Exclusive", b =>
                {
                    b.Property<int>("ExclusiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("exclusiveDec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exclusiveImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exclusiveTilte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExclusiveId");

                    b.ToTable("exclusives");
                });

            modelBuilder.Entity("Esraa_Store.Models.Featured", b =>
                {
                    b.Property<int>("FeaturedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Like")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featuredImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("featuredTilte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FeaturedId");

                    b.ToTable("featureds");
                });

            modelBuilder.Entity("Esraa_Store.Models.LastestPro", b =>
                {
                    b.Property<int>("LatestProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LatestProImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestProTilte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Like")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LatestProId");

                    b.ToTable("lastestPros");
                });

            modelBuilder.Entity("Esraa_Store.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
